// Generated by gencpp from file cardriver/encoder.msg
// DO NOT EDIT!


#ifndef CARDRIVER_MESSAGE_ENCODER_H
#define CARDRIVER_MESSAGE_ENCODER_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace cardriver
{
template <class ContainerAllocator>
struct encoder_
{
  typedef encoder_<ContainerAllocator> Type;

  encoder_()
    : left(0)
    , right(0)
    , leftPos(0)
    , rightPos(0)  {
    }
  encoder_(const ContainerAllocator& _alloc)
    : left(0)
    , right(0)
    , leftPos(0)
    , rightPos(0)  {
  (void)_alloc;
    }



   typedef int16_t _left_type;
  _left_type left;

   typedef int16_t _right_type;
  _right_type right;

   typedef int16_t _leftPos_type;
  _leftPos_type leftPos;

   typedef int16_t _rightPos_type;
  _rightPos_type rightPos;





  typedef boost::shared_ptr< ::cardriver::encoder_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::cardriver::encoder_<ContainerAllocator> const> ConstPtr;

}; // struct encoder_

typedef ::cardriver::encoder_<std::allocator<void> > encoder;

typedef boost::shared_ptr< ::cardriver::encoder > encoderPtr;
typedef boost::shared_ptr< ::cardriver::encoder const> encoderConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::cardriver::encoder_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::cardriver::encoder_<ContainerAllocator> >::stream(s, "", v);
return s;
}

} // namespace cardriver

namespace ros
{
namespace message_traits
{



// BOOLTRAITS {'IsFixedSize': True, 'IsMessage': True, 'HasHeader': False}
// {'cardriver': ['/home/user/catkin_ws/src/ROS_Serial/cardriver/msg'], 'std_msgs': ['/opt/ros/kinetic/share/std_msgs/cmake/../msg']}

// !!!!!!!!!!! ['__class__', '__delattr__', '__dict__', '__doc__', '__eq__', '__format__', '__getattribute__', '__hash__', '__init__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_parsed_fields', 'constants', 'fields', 'full_name', 'has_header', 'header_present', 'names', 'package', 'parsed_fields', 'short_name', 'text', 'types']




template <class ContainerAllocator>
struct IsFixedSize< ::cardriver::encoder_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::cardriver::encoder_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::cardriver::encoder_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::cardriver::encoder_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::cardriver::encoder_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::cardriver::encoder_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::cardriver::encoder_<ContainerAllocator> >
{
  static const char* value()
  {
    return "745db808f580869f3db96a00aaa84b88";
  }

  static const char* value(const ::cardriver::encoder_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x745db808f580869fULL;
  static const uint64_t static_value2 = 0x3db96a00aaa84b88ULL;
};

template<class ContainerAllocator>
struct DataType< ::cardriver::encoder_<ContainerAllocator> >
{
  static const char* value()
  {
    return "cardriver/encoder";
  }

  static const char* value(const ::cardriver::encoder_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::cardriver::encoder_<ContainerAllocator> >
{
  static const char* value()
  {
    return "int16 left\n\
int16 right\n\
int16 leftPos\n\
int16 rightPos\n\
";
  }

  static const char* value(const ::cardriver::encoder_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::cardriver::encoder_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.left);
      stream.next(m.right);
      stream.next(m.leftPos);
      stream.next(m.rightPos);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct encoder_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::cardriver::encoder_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::cardriver::encoder_<ContainerAllocator>& v)
  {
    s << indent << "left: ";
    Printer<int16_t>::stream(s, indent + "  ", v.left);
    s << indent << "right: ";
    Printer<int16_t>::stream(s, indent + "  ", v.right);
    s << indent << "leftPos: ";
    Printer<int16_t>::stream(s, indent + "  ", v.leftPos);
    s << indent << "rightPos: ";
    Printer<int16_t>::stream(s, indent + "  ", v.rightPos);
  }
};

} // namespace message_operations
} // namespace ros

#endif // CARDRIVER_MESSAGE_ENCODER_H
